Update autocomment-pr-raise.yml

diff --git a/.github/workflows/autocomment-pr-raise.yml b/.github/workflows/autocomment-pr-raise.yml
--- a/.github/workflows/autocomment-pr-raise.yml
+++ b/.github/workflows/autocomment-pr-raise.yml
@@ -1,4 +1,4 @@
-name: Auto Comment on PR
+name: Auto Comment on PR Open
 
 on:
   pull_request_target:
@@ -9,16 +9,15 @@ permissions:
   pull-requests: write
 
 jobs:
-  comment:
+  comment-on-open:
     runs-on: ubuntu-latest
-    permissions:
-      pull-requests: write
+
     steps:
-    - name: Add Comment to Pull Request
+    - name: Add Comment to Opened PR
       run: |
         COMMENT=$(cat <<EOF
         {
-          "body": "Thank you for submitting your pull request! 🙌 We'll review it as soon as possible. In the meantime, please ensure that your changes align with our [CONTRIBUTING.md](https://github.com/UppuluriKalyani/ML-Nexus/blob/main/CONTRIBUTING.md). If there are any specific instructions or feedback regarding your PR, we'll provide them here. Thanks again for your contribution! 😊"
+          "body": "👋 Thank you for opening this pull request! We appreciate your contribution to improving this project. Your PR is under review, and we'll get back to you shortly. \n\nTo help move the process along, please tag @UppuluriKalyani, @Neilblaze, and @SaiNivedh26 for a faster review!"
         }
         EOF
         )
@@ -30,7 +29,27 @@ jobs:
           -d "$COMMENT")
         cat response.json
         if [ "$RESPONSE" -ne 201 ]; then
-          echo "Failed to add comment"
+          echo "Failed to add comment on PR open"
+          exit 1
+        fi
+
+    - name: Add Reviewer to Pull Request
+      run: |
+        REVIEWERS=$(cat <<EOF
+        {
+          "reviewers": ["UppuluriKalyani","Neilblaze","SaiNivedh26"]
+        }
+        EOF
+        )
+        RESPONSE=$(curl -s -o response.json -w "%{http_code}" \
+          -X POST \
+          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+          -H "Accept: application/vnd.github.v3+json" \
+          https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/requested_reviewers \
+          -d "$REVIEWERS")
+        cat response.json
+        if [ "$RESPONSE" -ne 201 ]; then
+          echo "Failed to add reviewer"
           exit 1
         fi
       env:
